# Generated by Django 4.0.4 on 2022-04-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='board.subcategory'),
        ),
    ]
