# Generated by Django 4.0.4 on 2022-04-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=100),
            preserve_default=False,
        ),
    ]
